version: '3.8'

services:
  frontend:
    image: ghcr.io/edwardmartin22/mc_whitelist-frontend:main
    ports:
      - "8080:80"
    networks:
      - mc_net
    depends_on:
      - backend

  backend:
    image: ghcr.io/edwardmartin22/mc_whitelist-backend:main
    environment:
      - RCON_HOST=${RCON_HOST:-localhost}
      - RCON_PORT=${RCON_PORT:-25575}
      - RCON_PASSWORD=${RCON_PASSWORD:-}
      - PORTAL_NAME=${PORTAL_NAME:-My Custom Server}
    volumes:
      # Create an instructions.md file in the same folder as this compose file 
      # to override the default instructions shown on the portal!
      - ./instructions.md:/app/instructions.md:ro
    networks:
      - mc_net

networks:
  mc_net:
    driver: bridge
